### ISSUE TITLE
Set up a database for basic workspace management

### ISSUE THREAD

**Issue by priyanshumahey** [priyanshumahey/Team-Management#14]
Based off what we've already looked into, start creating a database that stores the following information:

- The name of your team
- URL of the newly created team
- Unique id of new team

Beyond deciding which database to use and setting it up, you also need to decide how to ensure everyone can collaborate on the same database.

**Deliverable:**
For this, I want a file that simply creates a new database when we create a new team. The deliverable for this is a function or file that when run, creates a new database. For now, it can hold some dummy data. This code should create the database with a name and folder selected by the user.

**For graphic**
Checkout Backend page on Figma. There's a frame called New Team.

**Comment by jtsang02** [comment]
See branch 14-set-up-a-database and the file `CreateDatabase.js`.

1. Please install MySQL server and workbench. I followed this video for reference: 
[Install MySQL Server and Workbench | MySQL Workbench Installation on Windows 10 | Simplilearn](https://www.youtube.com/watch?v=YSOY_NyOg40&ab_channel=Simplilearn)
	

2. Connect to your database. For now, we can connect locally so host should be set to 'localhost'  on line 17 of CreateDatabase.js.  I also ran into access permissions so I made a new user by running the `createUser.sql` script.  Change username and password as appropriate.

3. When running the script with a successful connection you should see readline prompts for entering a database name and folder. Upon successful creation you should see the following in terminal:

![Untitled picture](https://github.com/priyanshumahey/Team-Management/assets/77314661/e492d356-6f64-4dba-ab31-5fe728e4417b)
	
Viewed from MySQL Workbench:
	
![Untitled picture 2](https://github.com/priyanshumahey/Team-Management/assets/77314661/7893c6e1-09f0-447a-b28d-9cc8805497c5)

For now, the script just takes inputs from the command line for database name and folder.  The next steps I am working on are finding out how everyone can collaborate on the same database (i.e not locally), and writing backend routes that will call the functions in `CreateDatabase.js`.
