### ISSUE TITLE
Key assets, colors and sizing

### ISSUE THREAD

**Issue by priyanshumahey** [priyanshumahey/Team-Management#16]
This task is about creating a  page in Figma that holds a variety of helpful tools for creating new figma components. This should basically showcase the standard HTML elements such as:
- input
- button
- text (H1, H2, p, etc)
- other common base HTML things

The next part of this task involves creating some features that are not part of the base. For example:
- Header
- Footer
- Sidebar

On top of that, this task is about creating a toolkit to assist in future development thus you need to ensure you also consider the following:
- Colors to use
- Fonts to use
- Image guidelines
- Potentially explore logos

**Comment by dishaap** [comment]
https://www.figma.com/file/0TQou4Tu1fQvXni4RkHseb/Assets-and-Design-System?type=design&node-id=1%3A298&t=1OKf9JnGU5HL7VJD-1
